apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webapp
          image: us-central1-docker.pkg.dev/gcp-devops-training-389818/nginx-playground/webapp:40

