apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-08-19T20:14:16Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: web
  name: webapp
  namespace: default
  resourceVersion: "145935"
  uid: d8ebde12-91c5-4c35-8a89-41ac6803b097
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.64.25.175
  clusterIPs:
  - 10.64.25.175
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30192
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}