apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: GitOps-repo
    repoURL: 'https://github.com/yardenmev/GCP-Playground'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
